version: '3.1'

services:

  node:
    container_name: web-backend-node
    build:
      context: ./
    restart: always
    volumes:
      - .:/app
    command: npm run start:dev
    ports:
      - 3000:3000
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    image: mongo:4.4.11
    container_name: mongo-backend-node
    restart: always
    volumes:
      - ~/mongo/backend-node-mongo:/data/db
    # iniciar sem isso, configurar autenticacao e depois habilitar isso
    command: [--auth]

  mongo-express:
    image: mongo-express
    container_name: mongo-express-backend-node
    restart: always
    ports:
     - 9494:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: MuvqVw7bzZkOcUCIFeibTg
      ME_CONFIG_MONGODB_URL: mongodb://root:MuvqVw7bzZkOcUCIFeibTg@mongo:27017/
    depends_on:
      - mongo